pipeline {
    agent any
    stages {
        stage('clone') {
            steps {
                bat "mvn clean /MyApp"
            }
        }
        stage('Test') {
            steps {
                bat "mvn test /MyApp"
            }
        }
        stage('Deploy') {
            steps {
                bat "mvn package /MyApp"
            }
        }
    }
